# Generated by Django 4.2.3 on 2023-08-07 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images')),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('Mobile Phone', 'Mobile Phone'), ('Earphone', 'Earphone'), ('Laptop', 'Laptop'), ('Tablet', 'Tablet'), ('Smart Watch', 'Smart Watch'), ('BT Speaker', 'BT Speaker')], default='Mobile Phone', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order placed', 'Order placed'), ('Shipped', 'Shipped'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.products'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
